### ISSUE TITLE
Error with Forms.3.0

### ISSUE THREAD

**Issue by sadhac** [LeoJHarris/AdvancedEntry#8] opened 2018-05-17 21:19 UTC
Hi Leo

Thanks for providing the plugin. I am getting an error at runtime with Xamarin Forms 3.0: System.TypeLoadException
Could not resolve type with token 0100008b (from typeref, class/assembly Xamarin.Forms.Xaml.XamlResourceIdAttribute, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)

Please let me know whats the workaround to this?

Thank You

**Comment by LeoJHarris** [comment] 2018-05-17 21:36
Did you manage to resolve this issue?

**Comment by sadhac** [comment] 2018-05-18 09:22
Hi Leo

Seems to be an issue with the latest version of Forms 3.0.0.482510
I had to revert to 3.0.0.446417

Will let you know if there are any other issues.

Thanks

**Comment by LeoJHarris** [comment] 2018-05-18 09:23
Okay thanks for the heads up.

**Comment by sadhac** [comment] 2018-05-18 09:45
Hi Leo

This is the warnings I get now:
/Users/sadha/Documents/Projects/App/App.iOS/MTOUCH: Warning MT0109: The assembly 'Xamarin.Forms.Platform.iOS.dll' was loaded from a different path than the provided path (provided path: /Users/sadha/.nuget/packages/xamarin.forms/3.0.0.446417/lib/Xamarin.iOS10/Xamarin.Forms.Platform.iOS.dll, actual path: /Users/sadha/.nuget/packages/leojharris.xforms.plugin.enhancedentry/1.0.1/lib/Xamarin.iOS10/Xamarin.Forms.Platform.iOS.dll). (MT0109) (AdTAG.iOS)

**Comment by sadhac** [comment] 2018-05-18 10:03
Still getting the same error even with the reverted version of forms 3.

**Comment by LeoJHarris** [comment] 2018-05-18 10:07
Have you tried manually delete the bin/ and obj/ folders in your project directory and do a rebuild

**Comment by LeoJHarris** [comment] 2018-05-18 10:16
I dont think the issue is with this library, from what I found on the issue you are facing:

MT0109: The assembly '{0}' was loaded from a different path than the provided path (provided path: {1}, actual path: {2}).
This is a warning indicating that an assembly referenced by the application was loaded from a different location than requested.

This might mean that the app is referencing multiple assemblies with the same name, but from different locations, which might lead to unexpected results (only the first assembly will be used).

https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt0109-the-assembly-0-was-loaded-from-a-different-path-than-the-provided-path-provided-path-1-actual-path-2

You need to check your reference and remove the incorrect reference the error is telling you. 

This is my best bet

**Comment by sadhac** [comment] 2018-05-18 10:17
I have tried that now. Still no luck, removed them from both iOS and the Shared Project.
It builds successfully on Android, just an issue with iOS.

**Comment by sadhac** [comment] 2018-05-18 10:17
Thanks will check the references

**Comment by LeoJHarris** [comment] 2018-05-18 10:26
Great let me know if you get that working and we can close this issue

**Comment by LeoJHarris** [comment] 2018-05-18 10:26
Great let me know if you get that working

**Comment by sadhac** [comment] 2018-05-18 10:34
My references show Xamarin.iOS as version 0.0.0.0
Any help with this?

Thanks

**Comment by LeoJHarris** [comment] 2018-05-18 10:44
That reference is fine.

If I were you I would temporarily remove this library from your project via nuget, delete the package folder in here /Users/sadha/.nuget/ then look for the reference in the project if it still exists with the path pointing to /Users/sadha/.nuget/packages/leojharris.xforms.plugin.enhancedentry/1.0.1/lib/Xamarin.iOS10/Xamarin.Forms.Platform.iOS.dll and remove that, then delete the bin and obj, do a rebuild, if successful reinstall this library. 

One thing you should make sure is using some form of version control as well when things go pear sharped so you can revert back in history - it will save you a lot of hassle.

**Comment by sadhac** [comment] 2018-05-20 12:57
Hi Leo

Sorry for the delay. Yes I have moved to version control. Thanks for all the info. I have deleted the package in the nuget folder and still no luck. Will move it to a new solution and try again.

Thanks

**Comment by rbev** [comment] 2018-12-20 02:09
I was about to try out your library, but it looks like your nuget packaging is broken.

You are including a copy of the Xamarin libraries inside your android/ios platform libs which causes conflicts with the nuget references already in the project.

```
PS C:\Users\rhys.bevilaqua\.nuget\packages\leojharris.xforms.plugin.enhancedentry\1.0.3\lib\MonoAndroid10> dir


    Directory: C:\Users\rhys.bevilaqua\.nuget\packages\leojharris.xforms.plugin.enhancedentry\1.0.3\lib\MonoAndroid10


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        4/12/2018  10:14 PM          22096 FormsViewGroup.dll
-a----        4/12/2018  10:14 PM          22016 LeoJHarris.FormsPlugin.Abstractions.dll
-a----        4/12/2018  10:14 PM         164352 LeoJHarris.FormsPlugin.Droid.dll
-a----        4/12/2018  10:14 PM          29184 Xamarin.Android.Arch.Core.Common.dll
-a----        4/12/2018  10:14 PM          54368 Xamarin.Android.Arch.Lifecycle.Common.dll
-a----        4/12/2018  10:14 PM          32352 Xamarin.Android.Arch.Lifecycle.Runtime.dll
-a----        4/12/2018  10:14 PM          78456 Xamarin.Android.Support.Animated.Vector.Drawable.dll
-a----        4/12/2018  10:14 PM         144984 Xamarin.Android.Support.Annotations.dll
-a----        4/12/2018  10:14 PM        1766992 Xamarin.Android.Support.Compat.dll
-a----        4/12/2018  10:14 PM         594512 Xamarin.Android.Support.Core.UI.dll
-a----        4/12/2018  10:14 PM         239704 Xamarin.Android.Support.Core.Utils.dll
-a----        4/12/2018  10:14 PM         798800 Xamarin.Android.Support.Design.dll
-a----        4/12/2018  10:14 PM         433752 Xamarin.Android.Support.Fragment.dll
-a----        4/12/2018  10:14 PM         753248 Xamarin.Android.Support.Media.Compat.dll
-a----        4/12/2018  10:14 PM         333912 Xamarin.Android.Support.Transition.dll
-a----        4/12/2018  10:14 PM          41544 Xamarin.Android.Support.v4.dll
-a----        4/12/2018  10:14 PM        2114144 Xamarin.Android.Support.v7.AppCompat.dll
-a----        4/12/2018  10:14 PM          62552 Xamarin.Android.Support.v7.CardView.dll
-a----        4/12/2018  10:14 PM         794208 Xamarin.Android.Support.v7.MediaRouter.dll
-a----        4/12/2018  10:14 PM          69208 Xamarin.Android.Support.v7.Palette.dll
-a----        4/12/2018  10:14 PM         912992 Xamarin.Android.Support.v7.RecyclerView.dll
-a----        4/12/2018  10:14 PM          63584 Xamarin.Android.Support.Vector.Drawable.dll
-a----        4/12/2018  10:14 PM         713304 Xamarin.Forms.Core.dll
-a----        4/12/2018  10:14 PM         386672 Xamarin.Forms.Platform.Android.dll
-a----        4/12/2018  10:14 PM          17504 Xamarin.Forms.Platform.dll
-a----        4/12/2018  10:14 PM          94296 Xamarin.Forms.Xaml.dll
```

**Comment by LeoJHarris** [comment] 2018-12-20 02:57
Ill need to remove them and clean that up. Ill get a fix for this shortly.

**Comment by LeoJHarris** [comment] 2018-12-29 08:45
@rbev Hi there, 

Regarding "nuget packaging is broken" - do you mean you cannot install the nuget package?

I removed all Xamarin.Android.Support libs including Xamarin Forms and simply re-added Xamarin Forms which pulled all the required Support libs. This might have fixed the issue. I installed the nuget package to a blank Xamarin Forms project and I didn't have any issues.

**Comment by rbev** [comment] 2018-12-29 08:50
It causes issues when the version you are using differs between your package and the project consuming it, particularly when there are implicit transitive dependancies in the project structure. 

It won't always cause a problem but in general it is bad practice to ship libraries in your package that are sourced from another NuGet package rather than just declaring a dependancy on it in the manifest.

**Comment by LeoJHarris** [comment] 2018-12-30 22:25
@rbev the issue was the nuspec file was including all dll's - have resolved this now. I also added a package dependency on Xamarin.Forms.

**Comment by LeoJHarris** [comment] 2018-12-31 22:03
![annotation 2019-01-01 110257](https://user-images.githubusercontent.com/5468757/50568316-daf0cf80-0db4-11e9-8ed7-77a111597f5c.jpg)

**Closed as completed by LeoJHarris** 2018-12-31 22:03 UTC
Labels: bug
